---

# Ansible HANDLERS

- name: Regenerate grub config file
  ansible.builtin.command: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: Restart chronyd
  ansible.builtin.service:
    name: chronyd
    state: restarted
