---

# Ansible TASKS

- name: First task
  ansible.builtin.package:
    name: httpd
    state: present
  when: 
    - RHEL-08-123 | bool
  register: installed_package
  notify: restart apache

- name: Second task
  ansible.posix.firewalld:
    service: http
    state: enabled
    immediate: true
    permanent: true
  when:
    - RHEL-08-123 | bool
  
- name: Third task
  ansible.builtin.debug:
    vars: installed_package
  when:
    - RHEL-08-124 | bool ##
  ignore_errors: true

- name: Fourth task
  ansible.builtin.package:
    name: httpd
    state: present
  when: 
    - RHEL-08-123 | bool
  register: installed_package
  notify: reload firewall

- name: Fifth task
  ansible.posix.firewalld:
    service: http
    state: enabled
    immediate: true
    permanent: true
  when:
    - RHEL-08-124 | bool
  notify:
    - restart apache
    - lose my mind
  
- name: Sixth task
  ansible.builtin.debug:
    vars: installed_package
  when:
    - RHEL-08-123 | bool ##
  ignore_errors: true